SpendMoney/SpendMoney/ViewModels/ChargeForDreamViewModel.cs
using SpendMoney.Core.DTOs;

namespace SpendMoney.ViewModels
{
    public class ChargeForDreamViewModel
    {
        public List<UserAccountDto> UserAccounts { get; set; }
        public int DreamId { get; set; }
        public string DreamName { get; set; }
        public int SelectedAccountId { get; set; }
        public decimal Amount { get; set; }
    }
}

SpendMoney/SpendMoney/ViewModels/CreateDreamViewModel.cs
namespace SpendMoney.ViewModels
{
    public class CreateDreamViewModel
    {
        public string Name { get; set; }
        public int SaveType { get; set; }
        public DateTime EndDate { get; set; }
        public decimal TargetAmount { get; set; }
        public decimal CurrentAmount { get; set; }
    }
}

SpendMoney/SpendMoney/ViewModels/UserDreamViewModel.cs
namespace SpendMoney.ViewModels
{
    public class UserDreamViewModel
    {
        public string Name { get; set; }
        public int SaveType { get; set; }
        public DateTime EndDate { get; set; }
        public decimal TargetAmount { get; set; }
        public decimal CurrentAmount { get; set; }
        public decimal Percentage { get; set; }
    }
}

SpendMoney/SpendMoney/Controllers/UserDreamController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using SpendMoney.Core.Models;
using SpendMoney.Core.Services.Interfaces;
using SpendMoney.ViewModels;

namespace SpendMoney.Controllers
{
    [Route("[controller]")]
    public class UserDreamController : Controller
    {
        private readonly IUserDreamService _userDreamService;
        private readonly IAccountServicecs _accountService;
        private readonly ITransactionService _transactionService;
        private readonly IMapper _mapper;

        public UserDreamController(IMapper mapper, IUserDreamService userDreamService, IAccountServicecs accountService, ITransactionService transactionService)
        {
            _mapper = mapper;
            _userDreamService = userDreamService;
            _accountService = accountService;
            _transactionService = transactionService;
        }

        [HttpGet]
        [Route("CreateDream")]
        public IActionResult CreateDream()
        {
            return View();
        }

        [HttpPost]
        [Route("CreateDream")]
        public async Task<IActionResult> CreateDream(CreateDreamViewModel request)
        {
            var user = await _accountService.GetCurrentUser(User);
            var createRQ =_mapper.Map<CreateDreamRQ>(request);
            createRQ.UserId = user.Id;

            await _userDreamService.CreateDream(createRQ);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Route("Calculate")]
        public JsonResult Calculate(decimal targetAmount, decimal currentAmount, DateTime endDate, int saveType)
        {
            var needAmount = targetAmount - currentAmount;
            var dayCount = (endDate.Date - DateTime.Now.Date).TotalDays;

            string result = string.Empty;

            if(saveType == 1)
            {
                var weekCount = Math.Round(((decimal)dayCount) / 7, 1);
                var amount = Math.Round(needAmount / weekCount);

                result = "Кількість тижнів: " + weekCount + "<br/>" + "Сума кожного платежу: " + amount;
            }
            else if(saveType == 2)
            {
                var monthCount = Math.Round(((decimal)dayCount) / 30, 1);
                var amount = Math.Round(needAmount / monthCount, 2);

                result = "Кількість місяців: " + monthCount + "<br/>" + "Сума кожного платежу: " + amount;
            }
            else if(saveType == 3)
            {
                var amount = Math.Round(needAmount / (decimal)dayCount, 2);

                result = "Кількість днів: " + dayCount + "<br/>" + "Сума кожного платежу: " + amount;
            }

            return new JsonResult(result);
        }

        [Route("ChargeForDream")]
        [HttpGet]
        public async Task<IActionResult> ChargeForDream(int dreamId)
        {
            var user = await _accountService.GetCurrentUser(User);
            var accounts = await _accountService.GetAccountsByUserId(user.Id);
            var dream = await _userDreamService.GetDreamId(dreamId);

            var viewModel = new ChargeForDreamViewModel
            {
                DreamId = dreamId,
                UserAccounts = accounts,
                Amount = dream.EachPayAmount,
                DreamName = dream.Name
            };

            return View(viewModel);
        }

        [Route("ChargeForDream")]
        [HttpPost]
        public async Task<IActionResult> ChargeForDream(ChargeForDreamViewModel request)
        {
            ModelState.Remove("UserAccounts");

            var user = await _accountService.GetCurrentUser(User);

            if (!ModelState.IsValid)
            {
                var accounts = await _accountService.GetAccountsByUserId(user.Id);

                request.UserAccounts = accounts;

                return View(request);
            }

            await _transactionService.CreateTransaction(new CreateTransactionRQ
            {
                AccountId = request.SelectedAccountId,
                Amount = request.Amount,
                Description = "Перерахування на мрію " + request.DreamName,
                TransactionType = TransactionTypes.Transfer,
                UserDreamId = request.DreamId,
                UserId = user.Id,
            });

            return RedirectToAction("Index", "Home");
        }
    }
}

SpendMoney/SpendMoney/Views/UserDream/ChargeForDream.cshtml
@model ChargeForDreamViewModel

<div class="container" style="width: 50%">
    <div class="text-center">
        <h4>Поповнення мрії</h4>
    </div>

     <form class="mx-1 mx-md-4" asp-controller="UserDream" asp-action="ChargeForDream" method="post">
        <div class="mb-3">
            <label class="form-label" asp-for="SelectedAccountId">Аккаунт для переводу</label>
            <select asp-for="SelectedAccountId" class="form-control" style="">
                @{
                    var first = true;

                    foreach(var acc in Model.UserAccounts)
                    {
                        if (first)
                        {
                            <option selected value="@acc.AccountId">@acc.Name (@acc.Amount @acc.CurrencyShortName)</option>
                            first = false;
                        }
                        else
                        {
                            <option value="@acc.AccountId">@acc.Name (@acc.Amount @acc.CurrencyShortName)</option>
                        }
                    }
                }
            </select>
            <p class="text-danger">@Html.ValidationMessageFor(m => m.SelectedAccountId)</p>
        </div>

        <div class="mb-3">
            <label class="form-label" asp-for="Amount">Сума накопичення</label>
            <input type="number" asp-for="Amount" step="0.01" class="form-control"/>
            <p class="text-danger">@Html.ValidationMessageFor(m => m.Amount)</p>
        </div>

        <input type="hidden" asp-for="DreamId" />
        <input type="hidden" asp-for="DreamName" />

        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
            <button type="submit" class="btn btn-primary btn-lg">Перерахувати</button>
        </div>
    </form>
</div>

SpendMoney/SpendMoney/Views/UserDream/CreateDream.cshtml
@model CreateDreamViewModel


<div class="container h-100" style="width: 65%;">
    <div class="card">
        <div class="card-header">
            <div class="text-center mb-3" style="width: 100%">
                <h4>Створення нової мрії</h4>    
            </div>
        </div>
        <div class="card-body">
            <form class="mx-1 mx-md-4" asp-controller="UserDream" asp-action="CreateDream" method="post">
                <div class="mb-3">
                    <label class="form-label" asp-for="Name">Назва мрії</label>
                    <input type="text" asp-for="Name" class="form-control"/>
                    <p class="text-danger">@Html.ValidationMessageFor(m => m.Name)</p>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="SaveType">Тип внеску</label>
                    <select asp-for="SaveType" class="form-control" style="">
                        <option selected value="1">Щотижневий</option>
                        <option value="2">Щомісячний</option>
                        <option value="3">Щоденний</option>
                    </select>
                    <p class="text-danger">@Html.ValidationMessageFor(m => m.SaveType)</p>
                </div>

                <div class="mb-3">
                    <div class="form-group">
                        <label for="inputDate">Дата закінчення накопичення</label>
                        <input id="start-date-input" asp-for="EndDate" type="date" class="form-control">
                    </div>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="TargetAmount">Сума накопичення</label>
                    <input type="number" asp-for="TargetAmount" step="0.01" class="form-control"/>
                    <p class="text-danger">@Html.ValidationMessageFor(m => m.TargetAmount)</p>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="CurrentAmount">Поточна сума</label>
                    <input type="number" asp-for="CurrentAmount" step="0.01" class="form-control"/>
                    <p class="text-danger">@Html.ValidationMessageFor(m => m.CurrentAmount)</p>
                </div>

                <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <a id="calc_btn" class="btn btn-primary btn-lg">Розрахувати</a>
                </div>

                <div id="calc" class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">

                </div>

                <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <button type="submit" class="btn btn-primary btn-lg">Створити</button>
                </div>
            </form>
        </div>
    </div>
</div>


<script>
$(document).ready(function() {
    $('#calc_btn').on('click', function() {
        let targetAmount = $('#TargetAmount').val();
        let currentAmount = $('#CurrentAmount').val();
        let saveType = $('#SaveType').val();
        let endDate = $('#start-date-input').val();

        $.get('/UserDream/Calculate?targetAmount=' + targetAmount + '&currentAmount=' + currentAmount 
            + '&saveType=' + saveType + '&endDate=' + endDate, function(data) {
            if (data) {
                $('#calc').html(data);
            }
        });
    });
});
</script>