SpendMoney/SpendMoney/ViewModels/AddMoneyToCategoryViewModel.cs
using SpendMoney.Core.DTOs;

namespace SpendMoney.ViewModels
{
    public class AddMoneyToCategoryViewModel
    {
        public int AccountId { get; set; }
        public CategoryDto Category { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public List<UserAccountDto> UserAccounts { get; set; }
    }
}

SpendMoney/SpendMoney/ViewModels/AddMoneyTransactionToAccountViewModel.cs
using SpendMoney.Core.DTOs;

namespace SpendMoney.ViewModels
{
    public class AddMoneyTransactionToAccountViewModel
    {
        public UserAccountDto Account { get; set; }
        public decimal AmountToAdd { get; set; }
        public string Description { get; set; }
    }
}

SpendMoney/SpendMoney/ViewModels/RemoveMoneyTransactionFromAccountViewModel.cs
using SpendMoney.Core.DTOs;

namespace SpendMoney.ViewModels
{
    public class RemoveMoneyTransactionFromAccountViewModel
    {
        public UserAccountDto Account { get; set; }
        public List<CategoryDto> Categories { get; set; }
        public int CategoryId { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
    }
}

SpendMoney/SpendMoney/ViewModels/TransferToAccountViewModel.cs
using SpendMoney.Core.DTOs;

namespace SpendMoney.ViewModels
{
    public class TransferToAccountViewModel
    {
        public UserAccountDto Account { get; set; }
        public List<UserAccountDto> UserAccounts { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public int ToAccountId { get; set; }
    }
}

SpendMoney/SpendMoney/Controllers/TransactionController.cs
using Microsoft.AspNetCore.Mvc;
using SpendMoney.Core.DTOs;
using SpendMoney.Core.Models;
using SpendMoney.Core.Services.Interfaces;
using SpendMoney.ViewModels;

namespace SpendMoney.Controllers
{
    [Route("[controller]")]
    public class TransactionController : Controller
    {
        private readonly IAccountServicecs _accountService;
        private readonly ITransactionService _transactionService;
        private readonly ICategoryService _categoryService;

        public TransactionController(IAccountServicecs accountService, ITransactionService transactionService, ICategoryService categoryService)
        {
            _accountService = accountService;
            _transactionService = transactionService;
            _categoryService = categoryService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Route("AddMoneyTransactionToAccount")]
        public async Task<IActionResult> AddMoneyTransactionToAccount(int accountId)
        {
            var account = await _accountService.GetAccountById(accountId);

            var viewModel = new AddMoneyTransactionToAccountViewModel
            {
                Account = account
            };

            return View(viewModel);
        }

        [HttpPost]
        [Route("AddMoneyTransactionToAccount")]
        public async Task<IActionResult> AddMoneyTransactionToAccount(AddMoneyTransactionToAccountViewModel viewModel)
        {
            var user = await _accountService.GetCurrentUser(User);
            await _accountService.AddAmount(viewModel.Account.AccountId, viewModel.AmountToAdd);
            await _transactionService.CreateTransaction(new CreateTransactionRQ
            {
                Amount = viewModel.AmountToAdd,
                AccountId = viewModel.Account.AccountId,
                Description = viewModel.Description,
                UserId = user.Id,
                TransactionType = TransactionTypes.Add
            });

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Route("RemoveMoneyTransactionFromAccount")]
        public async Task<IActionResult> RemoveMoneyTransactionFromAccount(int accountId)
        {
            var user = await _accountService.GetCurrentUser(User);

            var viewModel = new RemoveMoneyTransactionFromAccountViewModel
            {
               Account = await _accountService.GetAccountById(accountId),
               Categories = await _categoryService.GetCategoryListByUserId(user.Id)
            };

            return View(viewModel);
        }

        [HttpPost]
        [Route("RemoveMoneyTransactionFromAccount")]
        public async Task<IActionResult> RemoveMoneyTransactionFromAccount(RemoveMoneyTransactionFromAccountViewModel viewModel)
        {
            var user = await _accountService.GetCurrentUser(User);
            await _transactionService.CreateTransaction(new CreateTransactionRQ
            {
                AccountId = viewModel.Account.AccountId,
                Description = viewModel.Description,
                UserId = user.Id,
                TransactionType = TransactionTypes.Spend,
                CategoryId = viewModel.CategoryId,
                Amount = viewModel.Amount
            });

            await _accountService.RemoveAmount(viewModel.Account.AccountId, viewModel.Amount);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Route("TransferToAccount")]
        public async Task<IActionResult> TransferToAccount(int accountId)
        {
            var user = await _accountService.GetCurrentUser(User);
            var account = await _accountService.GetAccountById(accountId);
            var foundAccounts = await _accountService.GetAccountsByUserId(user.Id);

            var viewModel = new TransferToAccountViewModel
            {
                Account = account,
                UserAccounts = foundAccounts.Where(x => x.AccountId != account.AccountId).ToList()
            };

            return View(viewModel);
        }

        [HttpPost]
        [Route("TransferToAccount")]
        public async Task<IActionResult> TransferToAccount(TransferToAccountViewModel viewModel)
        {
            var user = await _accountService.GetCurrentUser(User);

            var transactionId = await _transactionService.CreateTransaction(new CreateTransactionRQ
            {
                AccountId = viewModel.Account.AccountId,
                Description = viewModel.Description,
                UserId = user.Id,
                TransactionType = TransactionTypes.Transfer,
                Amount = viewModel.Amount,
                TransferToAccountId = viewModel.ToAccountId
            });

            await _accountService.RemoveAmount(viewModel.Account.AccountId, viewModel.Amount);

            var transaction = await _transactionService.GetTransactionById(transactionId);
            await _accountService.AddAmount(viewModel.ToAccountId, transaction.Amount);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Route("AddMoneyToCategory")]
        public async Task<IActionResult> AddMoneyToCategory(int categoryId)
        {
            var user = await _accountService.GetCurrentUser(User);
            var category = await _categoryService.GetCategoryById(categoryId);
            var userAccounts = await _accountService.GetAccountsByUserId(user.Id);

            var viewModel = new AddMoneyToCategoryViewModel
            {
                Category = category,
                UserAccounts = userAccounts
            };

            return View(viewModel);
        }

        [HttpPost]
        [Route("AddMoneyToCategory")]
        public async Task<IActionResult> AddMoneyToCategory(AddMoneyToCategoryViewModel viewModel)
        {
            ModelState.Remove("UserAccounts");
            ModelState.Remove("Category.Name");
            ModelState.Remove("Category.Color");
            ModelState.Remove("Category.Image");
            ModelState.Remove("Category.Description");

            var user = await _accountService.GetCurrentUser(User);

            if (ModelState.IsValid == false)
            {
                var category = await _categoryService.GetCategoryById(viewModel.Category.Id);
                var userAccounts = await _accountService.GetAccountsByUserId(user.Id);

                viewModel.Category = category;
                viewModel.UserAccounts = userAccounts;

                return View(viewModel);
            }

            var transactionId = await _transactionService.CreateTransaction(new CreateTransactionRQ
            {
                AccountId = viewModel.AccountId,
                Description = viewModel.Description,
                UserId = user.Id,
                TransactionType = TransactionTypes.Spend,
                Amount = viewModel.Amount,
                CategoryId = viewModel.Category.Id
            });

            await _accountService.RemoveAmount(viewModel.AccountId, viewModel.Amount);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Route("History")]
        public async Task<IActionResult> History()
        {
            //set accounts and cats
            var userId = (await _accountService.GetCurrentUser(User)).Id;
            var accs = await _accountService.GetAccountsByUserId(userId);
            var cats = await _categoryService.GetCategoryListByUserId(userId);

            var foundTransactions = await _transactionService.GetTransactionByFilter(new TransactionFilter
            {
                UserId = (await _accountService.GetCurrentUser(User)).Id
            });

            var transactionsForChart = foundTransactions.Where(x => x.TransactionType == (int)TransactionTypes.Spend).ToList();
            var allSum = transactionsForChart.Sum(x => x.Amount);
            var categoryNameList = transactionsForChart.Select(x => x.Category.Name.ToString()).Distinct().ToList();

            List<decimal> values = new List<decimal>();
            
            foreach (var catname in categoryNameList)
            {
                var s = transactionsForChart.Where(x => x.Category.Name == catname).ToList().Sum(x => x.Amount);
                values.Add(Math.Round(((s / allSum) * 100), 2));
            }

            var categoryNameListForChart = String.Join(',', categoryNameList);
            var valuesForChart = String.Join(',', values);

            return View(new TransactionHistoryViewModel
            {
                UserAccounts = accs,
                Categories = cats,
                Transactions = foundTransactions,
                CategoryListForChart = categoryNameListForChart,
                CategoryValueListForChart = valuesForChart
            });
        }

        [HttpPost]
        [Route("History")]
        public async Task<IActionResult> History(TransactionHistoryViewModel viewModel)
        {
            List<int> accountIds = new List<int>();
            List<int> categoryIds = new List<int>();
            DateTime? startDate = null;
            DateTime? endDate = null;

            if (!String.IsNullOrEmpty(viewModel.StartDate))
            {
                startDate = DateTime.Parse(viewModel.StartDate);
            }

            if (!String.IsNullOrEmpty(viewModel.EndDate))
            {
                endDate = DateTime.Parse(viewModel.EndDate);
            }

            if (!String.IsNullOrEmpty(viewModel.AccountId))
            {
                if (viewModel.AccountId[0] == ',')
                {
                    viewModel.AccountId = viewModel.AccountId.Remove(0, 1);
                }
                
                viewModel.AccountId.Split(',').ToList().ForEach(x => accountIds.Add(Convert.ToInt32(x)));
            }

            if (!String.IsNullOrEmpty(viewModel.CategoryId))
            {
                if (viewModel.CategoryId[0] == ',')

SpendMoney/SpendMoney/Views/Transaction/AddMoneyToCategory.cshtml
@model AddMoneyToCategoryViewModel

<div class="container d-flex justify-content-center">
    <div class="card" style="width: 50%">
        <div class="card-header">
            <div class="row">
                <div class="col-2">
                    <i style="background: @Model.Category.Color"><img src="@Model.Category.Image" width="30px"/></i>
                </div>
                <div class="col">
                    <h5>Додавання витрат коштів до категорії @Model.Category.Name</h5>
                </div>
            </div>
        </div>

        <div class="card-body d-flex justify-content-center">
            <form class="mx-1 mx-md-4" asp-controller="Transaction" asp-action="AddMoneyToCategory" method="post">
                <div class="d-flex row">

                <div class="col">
                    <label class="form-label" asp-for="Amount">Сума</label>
                    <input type="number" asp-for="Amount" step="0.01" class="form-control"/>
                </div>

                <div class="w-100"></div>

                <div class="col">
                    <label class="form-label" asp-for="Description">Опис</label>
                    <input type="text" asp-for="Description" step="0.01" class="form-control"/>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="AccountId">Оберіть рахунок</label>
                    <select asp-for="AccountId" class="form-control" style="">
                            @{
                                bool first = true;
                                foreach(var account in Model.UserAccounts)
                                {
                                    if (first)
                                    {
                                        <option selected value="@account.AccountId">@account.Name</option>
                                        first = false;
                                    }
                                    else
                                    {
                                     <option value="@account.AccountId">@account.Name</option>   
                                    }
                                }   
                            }
                
                    </select>
                    <p class="text-danger">@Html.ValidationMessageFor(m => m.AccountId)</p>
                </div>
                
                <div class="w-100"></div>
                <input type="hidden" asp-for="AccountId" value="@Model.AccountId" />
                <input type="hidden" asp-for="Category.Id" value="@Model.Category.Id" />

                
                <button type="submit" class="btn btn-primary mt-3">Підтвердити</button>
            </div>
            </form>
        </div>
    </div>
</div>

<style>
    i {
      border-radius: 20px;
      font-size: 25px;
      text-align: center;
      border-radius:50%;
      display:inline-block;
      padding:10px;
      height: 50px;
    }

    img {
      display:block;
    }
</style>

SpendMoney/SpendMoney/Views/Transaction/AddMoneyTransactionToAccount.cshtml
@model AddMoneyTransactionToAccountViewModel

<div class="container d-flex justify-content-center">
    <div class="card" style="width: 50%">
        <div class="card-header">
            <div class="row">
                <div class="col-2">
                    <i style="background: @Model.Account.Color"><img src="@Model.Account.Image" width="30px"/></i>
                </div>
                <div class="col">
                    <h5>Додавання коштів до рахунку @Model.Account.Name</h5>
                </div>
            </div>
        </div>

        <div class="card-body d-flex justify-content-center">
            <form class="mx-1 mx-md-4" asp-controller="Transaction" asp-action="AddMoneyTransactionToAccount" method="post">
                <div class="d-flex row">
                <div class="col">
                    <div class="d-flex flex-column">
                        <div>Поточний баланс:</div>
                        <div><small>@Model.Account.Amount @Model.Account.CurrencyShortName</small></div>
                    </div>
                </div>

                <div class="col">
                    <label class="form-label" asp-for="AmountToAdd">Сума поповнення</label>
                    <input type="number" asp-for="AmountToAdd" step="0.01" class="form-control"/>
                </div>

                <div class="w-100"></div>

                <div class="col">
                    <label class="form-label" asp-for="Description">Опис</label>
                    <input type="text" asp-for="Description" step="0.01" class="form-control"/>
                </div>
                
                <div class="w-100"></div>
                <input type="hidden" asp-for="Account.AccountId" value="@Model.Account.AccountId" />

                
                <button type="submit" class="btn btn-primary mt-3">Створити</button>
            </div>
            </form>
        </div>
    </div>
</div>

<style>
    i {
      border-radius: 20px;
      font-size: 25px;
      text-align: center;
      border-radius:50%;
      display:inline-block;
      padding:10px;
      height: 50px;
    }

    img {
      display:block;
    }
</style>

SpendMoney/SpendMoney/Views/Transaction/History.cshtml
@model TransactionHistoryViewModel

<div class="container-fluid">
    <div class="row d-flex justify-content-center">
        <div class="col">
            <div class="dropdown">
              <button class="btn btn-default dropdown-toggle" type="button" 
                      id="dropdownMenu1" data-toggle="dropdown" 
                      aria-haspopup="true" aria-expanded="true"
                      style="width: 100%">Рахунки</button>

              <ul id="accountList" class="dropdown-menu account-checkbox-menu allow-focus" aria-labelledby="dropdownMenu1">

                    @foreach (var acc in Model.UserAccounts)
                    {
                         <li id="@acc.AccountId" >
                          <label>
                            <input type="checkbox">@acc.Name</label>
                        </li>   
                    }
  
              </ul>

            </div>
        </div>
        <div class="col">
            <div class="dropdown">
              <button class="btn btn-default dropdown-toggle" type="button" 
                      id="dropdownMenu1" data-toggle="dropdown" 
                      aria-haspopup="true" aria-expanded="true"
                      style="width: 100%">Категорії</button>

              <ul id="catList" class="dropdown-menu category-checkbox-menu allow-focus" aria-labelledby="dropdownMenu1">
  
                    @foreach (var cat in Model.Categories)
                    {
                        <li id="@cat.Id" >
                            <label><input type="checkbox">@cat.Name</label>
                        </li>   
                    }
    
              </ul>

            </div>
        </div>

        <div class="w-100"></div>

        <div class="col">
            <div class="form-group">
                <label for="inputDate">Дата початку</label>
                <input id="start-date-input" type="date" class="form-control">
              </div>
        </div>

        <div class="col">
            <div class="form-group">
                <label for="inputDate">Дата кінця</label>
                <input id="end-date-input" type="date" class="form-control">
              </div>
        </div>

        <div class="w-100"></div>

        <div class="col d-flex justify-content-center">
            <form asp-controller="Transaction" asp-action="History" method="post">
                <input type="hidden" asp-for="AccountId" value="@Model.AccountId" />
                <input type="hidden" asp-for="CategoryId" value="@Model.CategoryId" />
                <input type="hidden" asp-for="StartDate" value="@Model.StartDate" />
                <input type="hidden" asp-for="EndDate" value="@Model.EndDate" />

                <input type="hidden" asp-for="CategoryListForChart" value="@Model.CategoryListForChart" />
                <input type="hidden" asp-for="CategoryValueListForChart" value="@Model.CategoryValueListForChart" />

                <button id="test" type="submit" class="btn btn-primary mt-3">Пошук</button>
            </form>
        </div>
    </div>
    <div class="w-100"></div>

    <div class="row mb-5">
        <div class="col-7">
            <table class="table table-hover">
                <thead>
                <tr>
                  <th scope="col">Категорія</th>
                  <th scope="col">Рахунок</th>
                  <th scope="col">Опис</th>
                  <th scope="col">Дата</th>
                  <th scope="col">Сума</th>
                  <th scope="col"></th>
                  <th scope="col"></th>
                </tr>
              </thead>
                <tbody>
                    @if((Model?.Transactions?.Count ?? 0) > 0)
                    {
                        foreach (var tran in Model.Transactions.OrderByDescending(x => x.Date).ToList())
                        {
                            String rowClass = String.Empty;

                            if(tran.TransactionType == (int)TransactionTypes.Add)
                            {
                                rowClass = "table-success";
                            }
                            else if(tran.TransactionType == (int)TransactionTypes.Spend && tran.Category != null)
                            {
                                rowClass = "table-danger";
                            }
                            else if(tran.TransactionType == (int)TransactionTypes.Spend && tran.Category == null)
                            {
                                rowClass = "table-danger";
                            }
                            else if(tran.TransactionType == (int)TransactionTypes.Transfer)
                            {
                                rowClass = "table-secondary";
                            } 

                            <tr class="@rowClass">
                                <td>
                                    @if(!string.IsNullOrEmpty(tran?.Category?.Name))
                                    {
                                        <span>@tran.Category.Name</span>
                                    }

                                    @if(tran.TransactionType == (int)TransactionTypes.Transfer && tran.TransferAccountId != null)
                                    {
                                        <span>Перерахування до рахунку @Model.UserAccounts.First(x => x.AccountId == tran.TransferAccountId).Name</span>
                                    }
                                    else if(tran.TransactionType == (int)TransactionTypes.Transfer && tran.UserDreamId != null)
                                    {
                                        <span>@tran.Description</span>
                                    }
                                </td>
                                <td>@tran.UserAccount.Name</td>
                                <td>@tran.Description</td>
                                <td>@tran.Date.ToString("yyyy-MM-dd")</td>
                                <td>@tran.Amount</td>
                                <td><a class="btn btn-outline-secondary" asp-action="ChangeTransaction" asp-route-id="@tran.TransactionId"><img src="/images/change_icon.png" width="20px" /></a></td>
                                <td><a class="btn btn-outline-warning" asp-action="RemoveTransaction" asp-route-id="@tran.TransactionId"><img src="/images/krest.png" width="20px" /></a></td>
                            </tr>
                        }   
                    }
                </tbody>
            </table>
        </div>

        <div class="col">
            <canvas id="myChart" style="width:100%;max-width:600px"></canvas>
        </div>
    </div>
</div>

<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.css" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.js"></script>

<style>
    .category-checkbox-menu li label,
    .account-checkbox-menu li label {
        display: block;
        padding: 3px 10px;
        clear: both;
        font-weight: normal;
        line-height: 1.42857143;
        color: #333;
        white-space: nowrap;
        margin:0;
        transition: background-color .4s ease;
    }
    .category-checkbox-menu li input,
    .account-checkbox-menu li input, {
        margin: 0px 5px;
        top: 2px;
        position: relative;
    }

    .category-menu li.active label, 
    .account-menu li.active label{
        background-color: #cbcbff;
        font-weight:bold;
    }

    .category-checkbox-menu li label:hover,
    .category-checkbox-menu li label:focus,
    .account-checkbox-menu li label:hover,
    .account-checkbox-menu li label:focus {
        background-color: #f5f5f5;
    }

    .category-checkbox-menu li.active label:hover,
    .category-checkbox-menu li.active label:focus
    .account-checkbox-menu li.active label:hover,
    .account-checkbox-menu li.active label:focus {
        background-color: #b8b8ff;
    }
</style>

<script>
$(document).ready(function() {
    var xValues = $("#CategoryListForChart").val().split(',');
    var yValues = $("#CategoryValueListForChart").val().split(',');
    var barColors = [
      "#b91d47",
      "#00aba9",
      "#2b5797",
      "#e8c3b9",
      "#1e7145"
    ];

    new Chart("myChart", {
      type: "pie",
      data: {
        labels: xValues,
        datasets: [{
          backgroundColor: barColors,
          data: yValues
        }]
      },
      options: {
        title: {
          display: true,
          text: "Витрати за категоріями"
        }
      }
    });
});
    
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>

<script>
    //load data
    if ($('#StartDate').val().length > 0) {
        let s = $('#StartDate').val().split('-');

        let y = s[0];
        let m = s[1];
        let d = s[2];

        if (m.length == 1) {
            m = '0' + m;
        }

        if (d.length == 1) {
            d = '0' + d;
        }

        $('#start-date-input').val(y + '-' + m + '-' + d);
    }

    if ($('#EndDate').val().length > 0) {
        console.log($('#EndDate').val());
        let s = $('#EndDate').val().split('-');

        let y = s[0];
        let m = s[1];
        let d = s[2];

        if (m.length == 1) {
            m = '0' + m;
        }

        if (d.length == 1) {
            d = '0' + d;
        }

        $('#end-date-input').val(y + '-' + m + '-' + d);
    }

    if($("#AccountId").val().length > 0) {
        var x = new Array();
        x = $("#AccountId").val().split(",");

        let items = $(".account-checkbox-menu input");
        
        for (let i = 0; i < items.length; i++) {
            console.log(items[i].closest('li').id);
            if(x.includes(items[i].closest('li').id)){
                items[i].closest("li").classList.add('active');
                items[i].checked = true;
            }
        }
    }

    if($("#CategoryId").val().length > 0) {
        var x = new Array();
        x = $("#CategoryId").val().split(",");

        let items = $(".category-checkbox-menu input");
        
        for (let i = 0; i < items.length; i++) {
            console.log(items[i].closest('li').id);
            if(x.includes(items[i].closest('li').id)){
                items[i].closest("li").classList.add('active');
                items[i].checked = true;
            }
        }
    }

    $('#start-date-input').change(function() {
        if($('#start-date-input').val().length > 0){
            var date = new Date($('#start-date-input').val());
            var day = date.getDate();
            var month = date.getMonth() + 1;
            var year = date.getFullYear();

            $("#StartDate").val([year, month, day].join('-'));
        } else {
            $("#StartDate").val('');
        }
    });

$('#end-date-input').change(function() {
    if ($('#end-date-input').val().length > 0) {
        var date = new Date($('#end-date-input').val());
        var day = date.getDate();
        var month = date.getMonth() + 1;
        var year = date.getFullYear();

        $("#EndDate").val([year, month, day].join('-'));
    } else {
            $("#EndDate").val('');
        }
});

    $(".account-checkbox-menu").on("change", "input[type='checkbox']", function() {
       $(this).closest("li").toggleClass("active", this.checked);
       
        if ($(this).closest('li').hasClass('active')) {
            let id = $(this).closest('li').attr('id');
            var x = new Array();
            x = $("#AccountId").val().split(",");
            x.push(id);
            $("#AccountId").val(x.join(','));
        } else {
            let id = $(this).closest('li').attr('id');
            var x = new Array();
            x = $("#AccountId").val().split(",");
            x = x.filter(function(elem){
               return elem != id; 
            });
            $("#AccountId").val(x.join(','));
        }
    });

    $(".category-checkbox-menu").on("change", "input[type='checkbox']", function() {
       $(this).closest("li").toggleClass("active", this.checked);
       
        if ($(this).closest('li').hasClass('active')) {
            let id = $(this).closest('li').attr('id');
            var x = new Array();
            x = $("#CategoryId").val().split(",");
            x.push(id);
            $("#CategoryId").val(x.join(','));
        } else {
            let id = $(this).closest('li').attr('id');
            var x = new Array();
            x = $("#CategoryId").val().split(",");
            x = x.filter(function(elem){
               return elem != id; 
            });
            $("#CategoryId").val(x.join(','));
        }
    });

    $(document).on('click', '.allow-focus', function (e) {
      e.stopPropagation();
    });

$('#main-wrapper').removeClass('container').addClass('container-fluid');
</script>